# Generated by Django 2.2.10 on 2020-07-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_category_todos_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='priority_counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
