# Generated by Django 3.0.8 on 2020-07-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_todoitem_priority_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='priority',
            field=models.CharField(choices=[('HI', 'Высокий приоритет'), ('ME', 'Средний приоритет'), ('LO', 'Низкий приоритет')], default='ME', max_length=2, verbose_name='Приоритет'),
        ),
    ]
