# Generated by Django 3.0.8 on 2020-07-21 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20200720_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='priority_counter',
            field=models.TextField(blank=True),
        ),
    ]
