# Generated by Django 3.0.8 on 2020-07-21 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20200721_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_counter', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='priority_counter',
        ),
    ]
