# Generated by Django 3.0.8 on 2020-07-21 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20200721_0111'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high', models.CharField(default='High', max_length=15)),
                ('medium', models.CharField(default='Meduim', max_length=15)),
                ('low', models.CharField(default='Low', max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='priorcount',
            name='priority_counter',
            field=models.TextField(blank=True, default='{HI:0, ME:0, LO:0}'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='priority',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.PriorChoice'),
        ),
    ]
