# Generated by Django 3.0.8 on 2020-07-21 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20200721_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priorchoice',
            name='high',
        ),
        migrations.AddField(
            model_name='priorchoice',
            name='priority',
            field=models.CharField(default='High', max_length=15),
        ),
    ]
