# Generated by Django 3.0.8 on 2020-07-21 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20200721_0148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='priorchoice',
            old_name='priority',
            new_name='high',
        ),
    ]
